### ISSUE TITLE
Add usage to Readme.md

### ISSUE THREAD

**Issue by mspace** [bmbferreira/DatabasePath-cordova#1]
I had hardtime knowing how to use your plugin, therefore it would be useful to add usage section in your readme file:

# Usage

```
window.plugins.databasepath.getDatabasePath(function (fullDbFilePath) {
  // do something with the database filePath.
}, function (error) {
  console.log(error);
});
```

**Comment by mspace** [comment]
Created pull request.

**Comment by bmbferreira** [comment]
@mspace thanks for your contribution! 👍
I wrote this simple plugin a few years ago and at the time I didn't worry too much about documentation... 🙁
